name: Build

on:
  push:
    paths:
      - .github/workflows/main.yml
      - 'src/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
    tags:
      - '*'
    branches:
      - '**'

jobs:
  build-plugin-versions:
    name: 'Build Plugin Versions'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: Build for OBS >= 28
        uses: ./.github/actions/build
        with:
          obs-version: '28.0.0'
          plugin-output-path: 'linux-pipewire-audio-obs28.tar.gz'
      - name: 'Upload'
        uses: actions/upload-artifact@v4
        with:
          name: linux-pipewire-audio-obs28
          path: linux-pipewire-audio-obs28.tar.gz
      - name: Build for OBS >= 30.2
        uses: ./.github/actions/build
        with:
          obs-version: '30.2.0'
          additional-deps: 'uthash-dev libjansson-dev'
          additional-obs-cmake-flags: '-DOBS_CMAKE_VERSION=3'
          plugin-output-path: 'linux-pipewire-audio-obs30-2.tar.gz'
      - name: 'Upload'
        uses: actions/upload-artifact@v4
        with:
          name: linux-pipewire-audio-obs30-2
          path: linux-pipewire-audio-obs30-2.tar.gz